version: '3.5'

services:
  keystore:
    image: elastdocker/elasticsearch:${ELK_VERSION}
    build:
      context: sys/elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-keystore.sh
    user: "0"
    volumes:
        - ./sys/secrets:/secrets
        - ./sys/setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  certs:
    image: elastdocker/elasticsearch:${ELK_VERSION}
    build:
      context: sys/elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ./sys/secrets:/secrets
      - ./sys/setup/:/setup